//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISE_S16_WB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public long ID { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public long FromUserID { get; set; }
        public long ToUserID { get; set; }
        public string MessageContent { get; set; }
        public bool IsRead { get; set; }
    
        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
    }
}
