//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISE_S16_WB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLike
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long PostID { get; set; }
        public System.DateTime EventDateTime { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
